#madlib!
print('Welcome to the MadLib Generator!')
print("")
adjective_1 = raw_input ('Type in an adjective: ')
adjective_2 = raw_input ('Another adjective: ')
adjective_3 = raw_input ('And another adjective: ')
adjective_4 = raw_input ('One more adjective: ')
plural_animal = raw_input ('Plural animal (e.g, puppies): ')
verb = raw_input ('Now a verb: ')
plural_noun = raw_input ('Now a plural noun: ')
woman_musician = raw_input ('The first name of a woman musician: ')
beverage = raw_input ('A beverage: ')
plural_body_part = raw_input ('And finally, a plural body part: ')
print("")
print('Excellent choices! Here is your story...')
print('___________________________')
print('There once was a fearless programmer named ' + woman_musician)
print('who wanted to build a ') + adjective_2 + (' mobile app to ')
print('help ') + adjective_3 + plural_animal + (' find new homes.')
print("")
print woman_musician + (' stayed up all night, drinking lots of caffeinated ') + beverage + (' as she worked and worked trying to complete her ') + adjective_4 + (' program.')
print('Whenever ') + woman_musician + (' hit a dead end, she would exclaim *') + plural_noun + ('*!')
print("")
print('But she was not discouraged, and after a quick break to ') + verb + (' and clear her head, she got back to work.')
print("")
print('By morning, when the sun started to rise, she let out a big yawn and stretched her ') + plural_body_part + ('.')
print('Finally, she was done.')
print('___________________________')
